### PR TITLE
Complete rework of Modelica generator

### PR DESCRIPTION
**Pull request by robbr48**
Major improvements:
- Use Kinsol to solve algebraic equation systems
- Select lienar transform method for each model using Modelica annotations
- Apply variable limits by resetting delays instead of `dxLimit()` functions
- Support custom Hopsan functions
- Support algorithm sections and conditional statements (experimental)
- Improved symbolic simplifications for better performance

### CODE REVIEW

**Comment by robbr48** [comment]
I know that this is very hard to review, but I created a test library with some components that demonstrates some of the new features.

[ModelicaTest.zip](https://github.com/Hopsan/hopsan/files/5128944/ModelicaTest.zip)

**Comment by peterNordin** [comment]
QRandomGenerator is to new, consider using standard c++ random generator if possible

**Review by peterNordin — COMMENTED** [review]
Yes you are right, difficult to review, lots of complex code. Just browsed through it.
Would it be possible to add a test modelica model, that can be converted using the generator (and preferably simulated, but not sure if the generator tests can do that). Not sure how to verify the generated code though.

**Comment by peterNordin** [comment]
Also symhop test failes

**Comment by peterNordin** [comment]
Looks good now, but I just remembered in the GeneratorTest there is a test "Generator_Modelica" that runs but says its disbaled.
Should this test be fixed or removed ?

**Comment by peterNordin** [comment]
The unit test does not work with CMake, but I will try to fix it

**Comment by peterNordin** [comment]
There is a build error if 	DEVELOPMENT is not defined around line 1316, in GUIContainerObject.cpp

**Review by peterNordin — CHANGES_REQUESTED** [review]
Fix build issue when DEVELOPMENT is not defined

**Review by peterNordin — APPROVED** [review]

**Pull request merged**
