### PR TITLE
Remove duplicate activity diagram source files

### PR DESCRIPTION
**Pull request by robbr48**
Remove duplicate component source files. We keep the ones that were specified in [ActivityDiagramLib.xml](https://github.com/robbr48/hopsan/blob/remove_duplicate_components_activity_diagram/componentLibraries/defaultLibrary/Signal/ActivityDiagram/ActivityDiagramLib.xml).

### CODE REVIEW

**Review by peterNordin — CHANGES_REQUESTED** [review]
I dont think that the files, Makefile.Debug, Makefile.Release, ActivityDiagramLib.cc , ActivitiyDiagramLib.pro and compile.bat should be added.

I recommend `git add -u` instead of `git add .` which I guess is the reason these files were added.

**Comment by peterNordin** [comment]
Other than that, OK

**Comment by robbr48** [comment]
My bad. I have removed the extra files.

**Comment by peterNordin** [comment]
ActivityDiagramLib.cc , ActivitiyDiagramLib.pro and compile.bat still remain, remove them also

**Pull request merged**
