### PR TITLE
Pumps with external leakage

### PR DESCRIPTION
**Pull request by samuelkarnell**
Added pumps with external leakage ports in the extended library. The difference between VariableMachine and VariableMachineW is that the latter has a mechanical port.

### CODE REVIEW

**Review by robbr48 — CHANGES_REQUESTED** [review]
- `VariableMachine` only computes the pressures (`p=c+Zc*q`) when there is cavitation. They should always be computed. The second component does this correctly.
- Default parameters for the leakage coefficients should not be zero. It is very hard for the user to figure out which order of magnitude to use for these parameters if there is no default value to compare with.

**Comment by OwenDavid** [comment]
Does the internal and external leakage in these components correspond to the leakage coefficient in the fixed displacement pumps and motors from the standard library?

If so the following issue resolved the leakage units to be m^3/s/pa. 
https://github.com/Hopsan/hopsan/issues/2025

Should the same units be used for the Variable Machines too? I'm not sure what the academic precedent is here but the standard library has components with m^3/s/pa.

*Ideally, there would be one standard leakage unit across all similar components, i.e. displacement pumps/motors.*

**Comment by OwenDavid** [comment]
What are your thoughts on the following proposal regarding a leakage coefficient units converter?

https://github.com/Hopsan/hopsan/issues/2040

**Comment by samuelkarnell** [comment]
@OwenDavid I think it could be a nice feature, and of course the principle can be applied on other parameters as well. However, I'm not sure how the unit conversion is implemented today (it is done outside of the component code), so I'm not really the guy to answer. Anyway, I found a related discussion #1801.

**Comment by OwenDavid** [comment]
I have now answered my own question on this and have a working implementation of scaling the leakage coefficients.

It is very trivial so have a look at the issue again if you are interested.

**Review by robbr48 — APPROVED** [review]

**Pull request merged**
