### PR TITLE
Issue 1839 lookuptable textinput

### LINKED ISSUE #1839: Lookup table component with string CSV parameters
**Is your improvement request related to a problem? Please describe.**
Sometimes you just want to make a quick lookup table, without the hassle of external files.

**Describe the solution you'd like**
Lookup table component(s?) with string parameters accepting comma-separated values. These should be parsed at initialize and stored in arrays.

### PR DESCRIPTION
**Pull request by peterNordin**
At textblock parameter type and GUI edit capability to lookup table components
Resolves #1839

### CODE REVIEW

**Comment by peterNordin** [comment]
Each component has its own format, lookup 1d, 2d, 3d and plo. The format is already available in the component description. Maybe the description should be shown alongside the edit dialog, or a button that opens it can be added. 

The lines must en in a newline charcter, but those can not be entered in the main dilog, which is not suitable for this type of input anyway.
The main dialog seems to show the new-line characters as spaces, but I don't know what may happen if you try to edit the text inline, it might even break the text. Maybe the main text edit should be removed for this type of parameters. Or at least set to read-only. It is convenient to be able to hover over it to see the entire text without having to open the dilog.

**Comment by robbr48** [comment]
I think removing the line edit is the best solution. If it confuses me, it will for sure confuse other people as well :)

**Comment by peterNordin** [comment]
I made it read-only, so you can still hover it and see a tooltip with the data. Or select all and copy to external file or similar. Linebreaks seem to be preserved.

**Comment by peterNordin** [comment]
Also a fun thing I discovered, if you want to create a system parameter with CSV data, no special editor is available, but you can past multiple lines from a text editor into the text edit field and the line breaks will be preserved (but look like a space). Will need to fix a dialog for system parameters also, but maybe later.

**Pull request merged**
